### ISSUE TITLE
Users should not edit index.js when generating a policy

### ISSUE THREAD

**Issue by KNTH01** [trailsjs/generator-trailpack#13]
In the default Trails project, there is no policy so the `api/policies/index.js` is like this : 

``` js
'use strict'

module.exports = {}
```

When I generate a policy with `yo trails:policy Auth`, it update the `api/policies/index.js` like that :

``` js
'use strict'

module.exports = {}
exports.Auth = require('./Auth')
```

`module.exports = {}` shall be removed, otherwise no policies are exported !

**Comment by jaumard** [comment]
I think it's the wrong repo @KevinNTH :)

**Comment by KNTH01** [comment]
@jaumard Where should I post then ?
Because the command is `trails:policy Auth`... Which repo is responsible for generating the scaffolding ?

**Comment by jaumard** [comment]
This generator is only useful for create a custom trailpack :) `trails:policy` is manage by `generator-trails` ;)

**Comment by jaumard** [comment]
The error come from here https://github.com/trailsjs/trailpack-hapi/blob/master/archetype/api/policies/index.js

**Comment by jaumard** [comment]
So trailpack-hapi 
Same for express (https://github.com/trailsjs/trailpack-express/blob/master/archetype/api/policies/index.js)
