### ISSUE TITLE
Package.json only include lib files

### ISSUE THREAD

**Issue by jaumard** [trailsjs/generator-trailpack#7]
There a problem with the generated `package.json` cause it include only files under `lib` and ignore other files on `npm publish`.

Maybe we could remove this or put : 

```
"files": [
    "lib",
    "config",
    "archetype",
    "api"
  ],
```

All my trailpacks not working cause of this ^^ now it's ok but maybe we can make it more clear for everyone. What do you think @tjwebb ?

**Comment by tjwebb** [comment]
Yea I've run into this as well. I need to find where this is set and fix it

**Comment by jaumard** [comment]
Related to https://github.com/trailsjs/generator-trails/issues/28

**Comment by tjwebb** [comment]
resolved: https://github.com/trailsjs/generator-node/commit/2e5730ae5cd4a4183673339e52866ffe209f4a40
